version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: interview
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432