spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

reserve:
  words: 'admin,administrator,root'